---
- hosts: all
  become: true
  tasks:
    - name: install packages
      yum: pkg={{item}} state=latest
      with_items:
        - vim
        - tree
        - unzip
    - name: download terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
  roles:
    - fubarhouse.golang