---
- hosts: all
  tasks:
    - name: install packages
      yum: pkg={{item}} state=latest
      with_items:
        - git
        - vim
        - tree
        - unzip
      become: true
    - name: download terraform suite
      unarchive:
        src: "{{item}}"
        dest: /usr/local/bin
        remote_src: yes
      with_items:
        - https://releases.hashicorp.com/vault/0.9.0/vault_0.9.0_linux_amd64.zip
        - https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip
        - https://releases.hashicorp.com/consul/1.0.1/consul_1.0.1_linux_amd64.zip
        - https://releases.hashicorp.com/packer/1.1.2/packer_1.1.2_linux_amd64.zip
      become: true
    - name: bash profile
      copy:
        src: .bash_profile
        dest: /home/vagrant/.bash_profile
        owner: vagrant
        group: vagrant
        mode: 0644
    - name: git clone
      git:
        repo: https://github.com/pledge/terraforming.git
        dest: /home/vagrant/projects/terraforming


#  roles:
#    - fubarhouse.golang