# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  

  config.vm.define "consul" do |i|
    i.vm.network "private_network", ip: "172.28.128.4"
    i.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/consul.yml"
    end
  end

  config.vm.define "vault" do |i|
    i.vm.network "private_network", ip: "172.28.128.5"
    i.vm.provision :ansible do |ansible|
       ansible.playbook = "provisioning/vault.yml"
    end
  end

  # config.vm.define "terraform" do |i|
  #   i.vm.provision :ansible do |ansible|
  #     ansible.playbook = "provisioning/terraform.yml"
  #   end
  # end

end
